name: Build YouMod
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
   
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YouMod & Extract Dylibs
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.branch }}
          path: YouMod

      - name: Install dependencies
        run: brew install make ldid dpkg

      - name: Set PATH environment variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Get Theos commit
        run: |
          get_commit_hash() {
            local repo_url=$1
            git ls-remote "$repo_url" HEAD | awk '{print substr($1,1,7)}'
          }
          echo "THEOS_COMMIT=$(get_commit_hash "https://github.com/roothide/theos")" >> $GITHUB_ENV

      - name: Cache Theos
        id: cache-theos
        uses: actions/cache@v6
        with:
          path: theos
          key: YouMod-26.5-SDK-${{ env.THEOS_COMMIT }}

      - name: Setup Theos
        if: ${{ steps.cache-theos.outputs.cache-hit != 'true' }}
        run: |
            git clone --quiet --depth=1 --recurse-submodules https://github.com/roothide/theos.git
            git clone --quiet --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
            cd iOS-SDKs
            git sparse-checkout set --no-cone iPhoneOS26.5.sdk
            git checkout --quiet
            mv *.sdk "$THEOS/sdks"
            
      - name: Clone headers
        run: |
          if [ ! -d "$THEOS/include/YouTubeHeader" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git "$THEOS/include/YouTubeHeader"
          else
            cd $THEOS/include/YouTubeHeader
            git pull --quiet --force
            cd ${{ github.workspace }}
          fi
          
          if [ ! -d "$THEOS/include/PSHeader" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git "$THEOS/include/PSHeader"
          else
            cd $THEOS/include/PSHeader
            git pull --quiet --force
            cd ${{ github.workspace }}
          fi

      - name: Fix Theos od broken pipe issue
        run: sed -i '' 's/od -c "$i" | head/od -c "$i" 2>\/dev\/null | head/g' $THEOS/bin/convert_xml_plist.sh || true

      - name: Build and Extract Dylibs
        shell: bash
        run: |
          cd YouMod
          VERSION=$(grep '^Version:' control | cut -d ' ' -f2)
          echo "YOUMOD_VERSION=$VERSION" >> $GITHUB_ENV
          
          # البناء واستخراج الـ dylib الأول (arm64e)
          make clean package DEBUG=0 FINALPACKAGE=1
          DEB_FILE=$(ls packages/*.deb | head -n 1)
          mkdir -p temp_extracted
          dpkg-deb -x "$DEB_FILE" temp_extracted
          FOUND_DYLIB=$(find temp_extracted -name "*.dylib" | head -n 1)
          if [ -n "$FOUND_DYLIB" ]; then
            cp "$FOUND_DYLIB" "${{ github.workspace }}/dylib.youmod_${VERSION}_iphoneos-arm64e.dylib"
          fi
          rm -rf temp_extracted
          make clean

          # البناء واستخراج الـ dylib الثاني (rootless - arm64)
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          DEB_FILE=$(ls packages/*.deb | head -n 1)
          mkdir -p temp_extracted
          dpkg-deb -x "$DEB_FILE" temp_extracted
          FOUND_DYLIB=$(find temp_extracted -name "*.dylib" | head -n 1)
          if [ -n "$FOUND_DYLIB" ]; then
            cp "$FOUND_DYLIB" "${{ github.workspace }}/dylib.youmod_${VERSION}_iphoneos-arm64.dylib"
          fi
          rm -rf temp_extracted
          make clean

          # البناء واستخراج الـ dylib الثالث (roothide - arm)
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide
          DEB_FILE=$(ls packages/*.deb | head -n 1)
          mkdir -p temp_extracted
          dpkg-deb -x "$DEB_FILE" temp_extracted
          FOUND_DYLIB=$(find temp_extracted -name "*.dylib" | head -n 1)
          if [ -n "$FOUND_DYLIB" ]; then
            cp "$FOUND_DYLIB" "${{ github.workspace }}/dylib.youmod_${VERSION}_iphoneos-arm.dylib"
          fi
          rm -rf temp_extracted
          make clean

          cd ..
          
          # ضغط ملفات المشروع مباشرة إلى المجلد الرئيسي
          zip -r "${{ github.workspace }}/YouMod_Source_and_Project_${VERSION}.zip" YouMod -x "YouMod/.git/*"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
         name: Hamad plus v${{ env.YOUMOD_VERSION }} Package & Dylibs
         path: |
           ${{ github.workspace }}/dylib.youmod_*.dylib
           ${{ github.workspace }}/YouMod_Source_and_Project_*.zip
         if-no-files-found: error
         overwrite: true

      - name: Create a draft release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.YOUMOD_VERSION }}
          name: v${{ env.YOUMOD_VERSION }} 
          files: |
            dylib.youmod_*.dylib
            YouMod_Source_and_Project_*.zip
          draft: true
